Cms.Web.Mvc/Areas/Admin/Controllers/BlogController.cs
using Cms.Business.Dtos;
using Cms.Business.Services;
using Cms.Business.Services.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cms.Web.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BlogController : Controller
    {
        private readonly IPostService _postService;

		public BlogController(IPostService postService)
		{
			_postService = postService;
		}

		public IActionResult Index(int page = 1)
		{
			int maxPage = _postService.GetMaxPageCount();
			if (page > maxPage)
			{
				return Redirect("Blog?page=" + maxPage);
			}
			else if (page < 1)
			{
				return Redirect("Blog?page=" + 1);
			}
			var departmanDto = new DepartmentDto();
			
			ViewBag.currentPage = page;
			ViewBag.maxPage = maxPage;
			return View(_postService.GetAll(page));
		}
	}
}

Cms.Web.Mvc/Controllers/AuthController.cs
using Cms.Business.Services.Abstract;
using Cms.Data;
using Cms.Data.Entity;
using Cms.Web.Mvc.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Cms.Web.Mvc.Controllers
{

    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        private readonly AppDbContext _context;
        //private readonly UserService _userService;

        public AuthController(AppDbContext context, IUserService userService)
        {
            _context = context;
            _userService = userService;
        }

        public IActionResult Register() => View();

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userDb = _context.Users.FirstOrDefault(e => e.Email == model.EmailAddress);
                if (userDb != null)
                {
                    ModelState.AddModelError("EmailAddress", "Email exists!");
                    return View(model);
                }

                if (model.Password != model.Password2)
                {
                    ModelState.AddModelError("Password", "Passwords does not match!");
                    return View(model);
                }

                var newUser = new User()
                {
                    Email = model.EmailAddress,
                    Password = model.Password,
                    Name = model.Name,
                    Surname = model.Surname,
                    City = model.City,
                    Phone = model.Phone,
                    Roles = model.Roles,
                };
                _context.Users.Add(newUser);
                _context.SaveChanges();

                return RedirectToAction("RegisterSuccess");
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult RegisterSuccess() => View();

        // /auth/login
        public IActionResult Login(string? redirectUrl)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.FirstOrDefault(e => e.Email == model.EmailAddress);

                if (user == null)
                {
                    ModelState.AddModelError("EmailAddress", "Email could not be found!");
                    return View(model);
                }

                if (user.Password != model.Password)
                {
                    ModelState.AddModelError("Password", "Password is wrong!");
                    return View(model);
                }

                // Kimlik Bilgileri
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.Name, user.Name ?? ""),
                        new Claim(ClaimTypes.GivenName, user.Name ?? ""),
                        new Claim(ClaimTypes.Surname, user.Surname ?? ""),
                        new Claim(ClaimTypes.Email, model.EmailAddress)
                    };
                bool isAdmin = false;
                if (!string.IsNullOrEmpty(user.Roles))
                {
                    string[] roles = user.Roles.Split(',');
                    foreach (var role in roles)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, role));
                        if (role == "Admin") isAdmin = true;
                    }
                }

                // Kimlik
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Cüzdan
                var principal = new ClaimsPrincipal(identity);

                var props = new AuthenticationProperties()
                {
                    IsPersistent = model.RememberMe,
                    ExpiresUtc = DateTime.UtcNow.AddMinutes(15),
                };

                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        principal,
                        props
                    );

                if (isAdmin)
                {
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }

                return Redirect(returnUrl != "" ? returnUrl : "/");
            }

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return Redirect("/");
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ForgotPassword(ResetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.FirstOrDefault(e => e.Email == model.EmailAddress);

                if (user == null)
                {
                    ModelState.AddModelError("EmailAddress", "Email could not be found!");
                    return View(model);
                }

                _userService.SendResetPasswordEmail(user.Email);

                return RedirectToAction("ForgotPasswordSuccess");
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult ForgotPasswordSuccess() => View();

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ResetPassword(string EmailAddress)
        {
            if (EmailAddress == null)
            {
                ModelState.AddModelError("", "Invalid email adress.");
            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult ResetPassword(ResetPasswordViewModel model)
        {
            var user = _context.Users.FirstOrDefault(e => e.Email == model.EmailAddress);

            if (ModelState.IsValid)
            {

                if (model.Password != model.Password2)
                {
                    ModelState.AddModelError("Password", "Passwords does not match!");
                    return View(model);
                }

                if (user.Password == model.Password)
                {
                    ModelState.AddModelError("Password", "New password should be different than the old one!");
                    return View(model);
                }

                if (model.Password != null)
                {
                    user.Password = model.Password;
                    _context.SaveChanges();

                    return RedirectToAction("ResetPasswordSuccess");
                }
            }

            return View(model);
        }

        public IActionResult ResetPasswordSuccess() => View();
    }
}

Cms.Web.Mvc/Controllers/BlogController.cs
using Cms.Business.Dtos;
using Cms.Business.Services.Abstract;
using Cms.Web.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Cms.Web.Mvc.Controllers
{
	public class BlogController : Controller
	{
		private readonly IPostService _postService;
		private readonly ICommentService _commentService;
		private readonly IDepartmentService _departmentService;

		public BlogController(IPostService postService, ICommentService commentService, IDepartmentService departmentService)
		{
			_postService = postService;
			_commentService = commentService;
			_departmentService = departmentService;
		}

		public IActionResult Index(int page = 1, string? departman = null)
		{
			int maxPage = _postService.GetMaxPageCount(departman, true);
			if (page > maxPage)
			{
				return Redirect("Blog?page=" + maxPage + "&departman=" + departman);
			}
			else if (page < 1)
			{
				return Redirect("Blog?page=" + 1 + "&departman=" + departman);
			}
			var departmanDto = new DepartmentDto();
			if (departman != null)
			{
				departmanDto = _departmentService.GetByDepartmentSlug(departman);
				ViewBag.departman = departmanDto;
			}
			ViewBag.currentPage = page;
			ViewBag.maxPage = maxPage;
			return View(_postService.GetAll(page, departmanDto.Slug));
		}


		public IActionResult Detail(int id)
		{
			var post = MapToVm(_postService.GetById(id));

			return View(post);
		}

		[HttpPost]
		public IActionResult Detail(int id, BlogDetailViewModel vm)
		{
			var post = new BlogDetailViewModel();
			if (ModelState.IsValid)
			{
				var comment = new PostCommentDto { Comment = vm.Comment, CreatedAt = DateTime.Now, IsActive = true, PostDtoId = id, UserDto = null };
				if (HttpContext.User.Identity.IsAuthenticated)
				{
					comment.UserDtoId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
				}

				_commentService.Add(comment);
			}

			post = MapToVm(_postService.GetById(id));
			post.Comment = vm.Comment;
			return RedirectToAction(nameof(Detail));
		}

		private BlogDetailViewModel MapToVm(PostDto post)
		{
			return new BlogDetailViewModel { User = post.User, Comments = post.Comments, Content = post.Content, CreatedAt = post.CreatedAt, Departments = post.Departments, PostImageDto = post.PostImageDto, Title = post.Title, UpdatedAt = post.UpdatedAt };
		}
	}
}

Cms.Web.Mvc/Views/Blog/Detail.cshtml
@model BlogDetailViewModel
<section class="section blog-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-lg-12 mb-5">
                        <div class="single-blog-item">
                            <img src="~/images/blog/@Model.PostImageDto.ImagePath" alt="" class="img-fluid">

                            <div class="blog-item-content mt-5">
                                <div class="blog-item-meta mb-3">
                                    <span class="text-muted text-capitalize mr-3"><i class="icofont-comment mr-2"></i>@Model.Comments.Count Comments</span>
                                    <span class="text-black text-capitalize mr-3"><i class="icofont-calendar mr-2"></i>@Model.CreatedAt.ToShortDateString()</span>
                                </div>

                                <h2 class="mb-4 text-md">@Model.Title</h2>
                                <p>
                                    @Model.Content
                                </p>

                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="comment-area mt-4 mb-5">
                            @if (@Model.Comments != null)
                            {
                                <h4 class="mb-4">@Model.Comments.Count Comments </h4>
                                <ul class="comment-tree list-unstyled">
                                    @foreach (var c in Model.Comments)
                                    {
                                        <li class="mb-5">
                                            <div class="comment-area-box d-block d-sm-flex">

                                                @*<div class="comment-thumb">
                                        <img alt="" src="@c.UserDto.ImagePath" style="width: 70px">
                                        </div>*@

                                                <div class="block">

                                                    <div class="comment-info">
                                                        <h5 class="mb-1">@(@c.UserDto == null ? "Anonim" :c.UserDto.Name) @*@c.UserDto*@</h5>
                                                        <span>@(@c.UserDto == null ? "":@c.UserDto.City)</span>
                                                        <span class="date-comm">| Posted @c.CreatedAt.ToShortDateString()</span>
                                                    </div>

                                                    <div class="comment-content mt-3">
                                                        <p>
                                                            @c.Comment
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <h4 class="mb-4">There is no comments </h4>
                            }
                        </div>
                    </div>


                    <div class="col-lg-12">
                        <form asp-action="Detail" method="post" class="comment-form my-5" id="comment-form">
                            <h4 class="mb-4">Yorum yaz</h4>
                            @if (!Context.User.Identity.IsAuthenticated) {
                                <h6>İsminizin gözükmesi için <a asp-controller="Auth" asp-action="Login"> giriş yapın</a></h6>
                            }else

                            {
                            <h6>@Context.User.FindFirst(ClaimTypes.Name).Value @Context.User.FindFirst(ClaimTypes.Surname).Value Olarak giriş yapıldı </h6>
                            }

                            <textarea asp-for="Comment" class="form-control mb-4" cols="30" rows="5" required></textarea>

                            <input class="btn btn-main-2 btn-round-full" type="submit" name="submit-contact" id="submit_contact" value="Yorumu gönder">
                            <div asp-validation-summary="All"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar-wrap pl-lg-4 mt-5 mt-lg-0">
                    <div class="sidebar-widget search  mb-3 ">
                        <h5>Arama Yap</h5>
                        <form action="#" class="search-form">
                            <input type="text" class="form-control" placeholder="search">
                            <i class="ti-search"></i>
                        </form>
                    </div>


                    <div class="sidebar-widget latest-post mb-3">
                        <h5>Popüler Başlıklar</h5>

                        <div class="py-2">
                            <span class="text-sm text-muted">03 Mar 2018</span>
                            <h6 class="my-2"><a href="#">Los Angel's Düşünceli Yaşam</a></h6>
                        </div>

                        <div class="py-2">
                            <span class="text-sm text-muted">03 Mar 2018</span>
                            <h6 class="my-2"><a href="#">Vivamus molestie gravida turpis.</a></h6>
                        </div>

                        <div class="py-2">
                            <span class="text-sm text-muted">03 Mar 2018</span>
                            <h6 class="my-2"><a href="#">Fusce lobortis lorem at ipsum semper sagittis</a></h6>
                        </div>
                    </div>

                    <div class="sidebar-widget category mb-3">
                        <h5 class="mb-4">Departmanlar</h5>

                        <ul class="list-unstyled">
                            <li class="align-items-center">
                                <a href="#">İlaç</a>
                                <span>(14)</span>
                            </li>
                            <li class="align-items-center">
                                <a href="#">Medikal</a>
                                <span>(2)</span>
                            </li>
                            <li class="align-items-center">
                                <a href="#">Kalp</a>
                                <span>(10)</span>
                            </li>
                            <li class="align-items-center">
                                <a href="#">Ücretsiz danışmanlık</a>
                                <span>(5)</span>
                            </li>
                            <li class="align-items-center">
                                <a href="#">Labaratuar Testleri</a>
                                <span>(5)</span>
                            </li>
                        </ul>
                    </div>


                    <div class="sidebar-widget tags mb-3">
                        <h5 class="mb-4">Tags</h5>

                        <a href="#">Doktorlar</a>
                        <a href="#">Ajans</a>
                        <a href="#">Şirket</a>
                        <a href="#">İlaç</a>
                        <a href="#">Ameliyat</a>
                        <a href="#">Pazarlama</a>
                        <a href="#">Sosyal Medya</a>
                        <a href="#">Markalaşma</a>
                        <a href="#">Labaratuar</a>
                    </div>


                </div>
            </div>
        </div>
    </div>
</section>

Cms.Web.Mvc/Views/Blog/Index.cshtml
@model List<PostDto>
<section class="page-title bg-1">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block text-center">
                    <span class="text-white">Blog sayfamız</span>
                    <h1 class="text-capitalize mb-5 text-lg">@(ViewBag.departman != null ? ViewBag.departman.Name : "Blog postları")</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section blog-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h4>@(ViewBag.currentPage). Sayfa</h4>
                <div class="row">

                    @foreach (var item in Model)
                    {
                        <div class="col-lg-12 col-md-12 my-5">

                            <div class="blog-item">
                                <div class="blog-thumb">
                                    <img src="images/blog/@item.PostImageDto.ImagePath" alt="" class="img-fluid ">
                                </div>

                                <div class="blog-item-content">
                                    <div class="blog-item-meta mb-3 mt-4">
                                        <span class="text-muted text-capitalize mr-3">
                                            <i class="icofont-comment mr-2"></i>@(
                                        item.Comments == null ? "" : item.Comments.Count
                                        )
                                        </span>
                                        <span class="text-black text-capitalize mr-3"><i class="icofont-calendar mr-1"></i> @item.CreatedAt</span>
                                        <span>
                                            @foreach (var d in item.Departments)
                                            {
                                                <span class="mx-1">
                                                    @d.Name
                                                </span>
                                            }
                                        </span>
                                    </div>

                                    <h2 class="mt-3 mb-3"><a asp-controller="Blog" asp-action="detail" asp-route-id="@item.Id">@item.Title</a></h2>

                                    <a asp-controller="Blog" asp-action="detail" asp-route-id="@item.Id" target="_blank" class="btn btn-main btn-icon btn-round-full">Devam oku <i class="icofont-simple-right ml-2  "></i></a>
                                </div>
                            </div>

                        </div>
                    }


                    <div class="col-lg-12 col-md-12">
                        <nav class="pagination py-2 d-inline-block">
                            <div class="nav-links">
                                @if (ViewBag.maxPage > 1)
                                {
                                    @if (ViewBag.departman == null)
                                    {
                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="1"><i class="icofont-thin-double-left"></i></a>

                                        if (ViewBag.currentPage > 1 && ViewBag.currentPage < ViewBag.maxPage) //1. ve son sayfa olmaması durumu
                                        {

                                            <a class="page-numbers" asp-controller="Blog" asp-route-page="@(ViewBag.currentPage - 1)">@(ViewBag.currentPage - 1)</a>
                                            <span aria-current="page" class="page-numbers current">@ViewBag.currentPage</span>
                                            <a class="page-numbers" asp-controller="Blog" asp-route-page="@(ViewBag.currentPage + 1)">@(ViewBag.currentPage + 1)</a>

                                        }
                                        else
                                        {
                                            if (ViewBag.currentPage == 1)
                                            {
                                                <span aria-current="page" class="page-numbers current">@ViewBag.currentPage</span>
                                                for (int i = 1; i <= 2; i++)
                                                {
                                                    if (ViewBag.maxPage > 1 + i)
                                                    {
                                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="@(1+i)">@(1 + i)</a>
                                                    }@*asp-route-departman="@ViewBag.departman.Slug"*@
                                                }
                                            }
                                            if (ViewBag.currentPage == ViewBag.maxPage)
                                            {
                                                for (int i = 2; i >= 1; i--)
                                                {
                                                    if (ViewBag.maxPage - i != 0)
                                                    {
                                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="@(ViewBag.maxPage-i)">@(ViewBag.maxPage - i)</a>
                                                    } @*asp-route-departman="@ViewBag.departman.Slug"*@
                                                }
                                                <span aria-current="page" class="page-numbers current">@ViewBag.currentPage</span>
                                            }
                                        }
                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="@ViewBag.maxPage"><i class="icofont-thin-double-right"></i></a>
                                    }
                                    else
                                    {
                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="1" asp-route-departman="@ViewBag.departman.Slug"><i class="icofont-thin-double-left"></i></a>

                                        if (ViewBag.currentPage > 1 && ViewBag.currentPage < ViewBag.maxPage) //1. ve son sayfa olmaması durumu
                                        {

                                            <a class="page-numbers" asp-controller="Blog" asp-route-page="@(ViewBag.currentPage - 1)" asp-route-departman="@ViewBag.departman.Slug">@(ViewBag.currentPage - 1)</a>
                                            <span aria-current="page" class="page-numbers current">@ViewBag.currentPage</span>
                                            <a class="page-numbers" asp-controller="Blog" asp-route-page="@(ViewBag.currentPage + 1)" asp-route-departman="@ViewBag.departman.Slug">@(ViewBag.currentPage + 1)</a>

                                        }
                                        else
                                        {
                                            if (ViewBag.currentPage == 1)
                                            {
                                                <span aria-current="page" class="page-numbers current">@ViewBag.currentPage</span>
                                                for (int i = 1; i <= 2; i++)
                                                {
                                                    if (ViewBag.maxPage >= 1 + i)
                                                    {
                                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="@(1+i)" asp-route-departman="@ViewBag.departman.Slug">@(1 + i)</a>
                                                    }@*asp-route-departman="@ViewBag.departman.Slug"*@
                                                }
                                            }
                                            if (ViewBag.currentPage == ViewBag.maxPage)
                                            {
                                                for (int i = 2; i >= 1; i--)
                                                {
                                                    if (ViewBag.maxPage - i != 0)
                                                    {
                                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="@(ViewBag.maxPage-i)" asp-route-departman="@ViewBag.departman.Slug">@(ViewBag.maxPage - i)</a>
                                                    } @*asp-route-departman="@ViewBag.departman.Slug"*@
                                                }
                                                <span aria-current="page" class="page-numbers current">@ViewBag.currentPage</span>
                                            }
                                        }
                                        <a class="page-numbers" asp-controller="Blog" asp-route-page="@ViewBag.maxPage" asp-route-departman="@ViewBag.departman.Slug"><i class="icofont-thin-double-right"></i></a>
                                    }
                                }
                            </div>
                        </nav>
                    </div>

                </div>
            </div>
            @await Component.InvokeAsync("BlogSidebar")
        </div>
    </div>
</section>